# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_get_sp_dists_par
#'
#' @noRd
rcpp_get_sp_dists_par <- function(graph, vert_map_in, fromi, toi_in) {
    .Call(`_m4ra_rcpp_get_sp_dists_par`, graph, vert_map_in, fromi, toi_in)
}

